[project]
name = "webexmemebot"
version = "0.0.0"
description = "Webex-based meme generation bot using memegen.link."
readme = "README.md"
authors = [
    {name = "luketainton"},
]
requires-python = "<3.14,>=3.13"
dependencies = [
    "webex-bot<1.3.2,>=1.3.1",
    "pillow<12.3.1,>=12.3.0",
    "astroid<=4.3.1",
]

[dependency-groups]
dev = [
    "coverage<8.0.0,>=7.6.10",
    "pytest<9.1.2,>=9.1.1",
    "pre-commit<5.0.0,>=4.0.1",
    "pytest-github-actions-annotate-failures>=0.3.0",
]

[project.scripts]
meme = "app.main:main"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.black]
line-length = 120

[tool.ruff.lint]
ignore = ["EXE001"]
